dev.p2ptradehelper/frontend/urls.py
from django.urls import path
from . import views

app_name = 'frontend'

urlpatterns = [
    path('arbitration', views.arbitration, name='arbitration'),
    path('', views.landing, name="home"),
    path('oferta', views.download_oferta),
]

dev.p2ptradehelper/p2phelper/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('tradehelper.urls')),
    path('', include('frontend.urls')),
    path('', include('django_nextjs.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

dev.p2ptradehelper/tradehelper/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views

from . import views as app_views
from . import captcha

from .forms import UserLoginForm, SetPasswordUserForm
from django.contrib.auth.decorators import login_required

app_name = 'tradehelper'

urlpatterns = [
    path('profile', app_views.index, name='profile'),
    path('autopay', app_views.download_autopay, name='autopay_rules'),
    path('payment_complete', app_views.payment_complete, name='payment_complete'),
    path('payment_fail', app_views.payment_fail, name='payment_fail'),
    path('login', views.LoginView.as_view(authentication_form=UserLoginForm), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('register', captcha.check_recaptcha(app_views.register_request), name='register'),
    path('edit_profile', app_views.update_profile, name='edit_profile'),
    path('password_reset', captcha.check_recaptcha(app_views.password_reset_request), name="password_reset"),
    path('password_reset/done/',
         views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html',
                                                form_class=SetPasswordUserForm,
                                                success_url=reverse_lazy('tradehelper:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset/done/',
         views.PasswordResetCompleteView.as_view(template_name='tradehelper/passwords/password_reset_complete.html'),
         name='password_reset_complete'),

    # API
    path('api/chains/', login_required(app_views.ChainsList.as_view()), name="chains"),
    path('api/payment_notification/', app_views.NotificationListener.as_view(), name="payment_notification"),
    path('buy_subscription', login_required(app_views.get_subscription), name="buy_subscription"),
    path('unsubscribe', login_required(app_views.unsubscribe), name="unsubscribe"),
]

dev.p2ptradehelper/tradehelper/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth.models import User

from .models import Profile


class ProfileForm(UserCreationForm):
    email = forms.EmailField(required=True, label='Почта')

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for _object in self.fields.values():
            _object.widget.attrs.update({'class': 'form-control shadow-none', 'placeholder': _object.label})

        self.fields['username'].widget.attrs.update(
            {'class': 'form-control shadow-none', 'placeholder': 'Логин', 'type': 'text'})

    # Переопределяем подкласс Meta, перезаписывая кортеж fields с добавлением поля email
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2",)

    # Переопределяем метод save, определяя новому пользователю значение атрибута email
    def save(self, commit=True):
        user = super(ProfileForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'id': 'input_username', 'class': 'form-control shadow-none', 'placeholder': 'Логин',
                                                     'value': '{{ user.get_username }}', 'type': 'text'})
        self.fields['email'].widget.attrs.update({'id': 'input_email','class': 'form-control shadow-none',
                                                  'placeholder': 'Электронная почта', 'value': '{{ user.email }}',
                                                  'type': 'text'})


class ProfileImageForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('profile_photo', )

    def __init__(self, *args, **kwargs):
        super(ProfileImageForm, self).__init__(*args, **kwargs)
        self.fields['profile_photo'].widget.attrs.update(
            {'id': 'upload_photo', 'style': 'opacity: 0.0; position: relative; width: 100%; height:100%; '})


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'id': 'input_login', 'class': 'form-control shadow-none', 'placeholder': 'Логин', 'type': 'text'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'id': 'input_password','class': 'form-control shadow-none', 'placeholder': 'Пароль', 'type': 'password'}))


class PasswordResetUserForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(PasswordResetUserForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control shadow-none', 'placeholder': 'Почта', 'type': 'text'})


class SetPasswordUserForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(SetPasswordUserForm, self).__init__(*args, **kwargs)
        self.fields['new_password1'].widget.attrs.update(
            {'class': 'form-control shadow-none', 'placeholder': 'Новый пароль', 'type': 'password'})
        self.fields['new_password2'].widget.attrs.update(
            {'class': 'form-control shadow-none', 'placeholder': 'Повторите пароль', 'type': 'password'})

dev.p2ptradehelper/tradehelper/views.py
import datetime
import json
import os
import logging

from rest_framework import status

from .tasks import send_mail_task, charge_subscription

from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import BadHeaderError, send_mail
from django.db.models import Q
from django.http import HttpResponse, FileResponse, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib import messages
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.core.cache import cache
from rest_framework.views import APIView
from rest_framework.response import Response

from .forms import PasswordResetUserForm, SetPasswordUserForm
from .functions import buy_subscription

from .forms import ProfileForm, UserForm, ProfileImageForm
from django.conf import settings
from .modules import ChainForView, is_valid_filter, filter_chains

from .modules import serialize_chains, deserialize_chains
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

from .models import Order, get_next_payment_date, get_base_subscription
from p2phelper.celery import app

logger = logging.getLogger(__name__)

@login_required(login_url='tradehelper:login')
def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileImageForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and (User.objects.filter(email=user_form.cleaned_data["email"]).count() == 0 or
                                     user_form.cleaned_data["email"] == request.user.email):
            if profile_form.is_valid():
                profile_photo = profile_form.cleaned_data['profile_photo']
                if profile_photo:
                    if profile_photo.size / 1000 <= 1000:
                        profile_form.save()
                        user_form.save()
                        return redirect('tradehelper:profile')
                    else:
                        messages.info(request, "Допустимый размер изображения - до 1МБ")
                else:
                    user_form.save()
                    return redirect('tradehelper:profile')
            else:
                messages.info(request, "Загружаемый файл должен быть изображением")
        else:
            messages.info(request, "Имя пользователя или электронная почта уже заняты")
    user_form = UserForm(instance=request.user)
    profile_form = ProfileImageForm()
    return render(request, 'tradehelper/edit_profile.html', {
        'user_form': user_form,
        'image_form': profile_form,
    })


def register_request(request):
    if request.method == "POST":
        if request.recaptcha_is_valid:
            form = ProfileForm(request.POST)
            if form.is_valid() and User.objects.filter(email=form.cleaned_data["email"]).count() == 0:
                user = form.save()
                login(request, user)
                messages.success(request, "Вы успешно зарегистрированы")
                return redirect("tradehelper:profile")
            messages.error(request, "Ошибка регистрации. Проверьте введённые данные")
    form = ProfileForm()
    return render(request,
                  'tradehelper/register.html',
                  context={"register_form": form})


@login_required(login_url='tradehelper:login')
def index(request):
    return render(
        request,
        'tradehelper/profile.html',
        context={"next_payment_date": get_next_payment_date()})


def password_reset_request(request):
    if request.method == "POST":
        if request.recaptcha_is_valid:
            password_reset_form = PasswordResetUserForm(request.POST)
            if password_reset_form.is_valid():
                data = password_reset_form.cleaned_data['email']
                associated_users = User.objects.filter(Q(email=data))
                if associated_users.exists():
                    for user in associated_users:
                        send_mail_task.apply_async(args=["Password Reset Requested",
                                                         "tradehelper/passwords/password_reset_email.txt",
                                                         user.email,
                                                         {
                                                             'email': user.email,
                                                             'domain': 'p2ptradehelper.ru',
                                                             'site_name': 'P2PTradeHelper',
                                                             'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                                                             'user': user.username,
                                                             'token': default_token_generator.make_token(user),
                                                             'protocol': 'https',
                                                         }], queue="mail_queue")
                        return redirect("tradehelper:password_reset_done")
            else:
                messages.info(request, "Вы не прошли проверку Captcha")
        else:
            messages.info(request, "Вы не прошли проверку Captcha")
    password_reset_form = PasswordResetUserForm()
    return render(request=request, template_name='tradehelper/passwords/password_reset_form.html',
                  context={"password_reset_form": password_reset_form})


def new_password_confirm(request):
    set_password_form = SetPasswordUserForm()
    return render(request=request, template_name='registration/password_reset_confirm.html',
                  context={"form": set_password_form})


class NotificationListener(APIView):
    def post(self, request):
        try:
            logger.info("Payment notification is received")
            order_data = request.data
            logger.info(f"Order_data: {order_data}")
            user_order = Order.objects.get(id=int(order_data["OrderId"]))
            if user_order.status != "CONFIRMED":
                logger.info(f"User order that we find: {user_order.__dict__}")
                user_order.status = order_data["Status"]
                user_order.save()
                if order_data["Success"] and order_data["Status"] == "CONFIRMED":
                    logger.info("OMG! Success in order operation!")
                    user = user_order.user
                    user.profile.subscription = get_base_subscription()
                    logger.info(f"We have issued a subscription!: {user.profile.subscription}")
                    user.profile.subscription.rebill_id = order_data["RebillId"]
                    logger.info(f"NEXT CHARGING: {user.profile.subscription.date_end}")
                    seconds_to_charge = (user.profile.subscription.date_end - datetime.datetime.now()).total_seconds()
                    logger.info(f"Seconds to charge: {seconds_to_charge}")
                    charging_id = charge_subscription.apply_async(args=[user.id,],
                                                                  countdown=seconds_to_charge,
                                                                  queue="subscription_queue")
                    mailing_id = send_mail_task.apply_async(args=["Подписка оформлена",
                                                     "tradehelper/subscription.txt",
                                                     user.email,
                                                     {
                                                         'user': user.username,
                                                         'next_payment': user.profile.subscription.date_end.strftime("%d.%m.%Y"),
                                                     }], queue="mail_queue")

                    seconds_to_notify = seconds_to_charge - 86400

                    notify_mailing_id = send_mail_task.apply_async(args=["Подписка на P2PTradeHelper",
                                                                  "tradehelper/subscription_notify.txt",
                                                                  user.email,
                                                                  {
                                                                      'user': user.username,
                                                                  }], countdown=seconds_to_notify, queue="mail_queue")
                    user.profile.subscription.charge_task = str(charging_id)
                    user.profile.subscription.mailing_task = str(mailing_id) + '|' + str(notify_mailing_id)
                    user.profile.subscription.save()
                    user.save()
                    return HttpResponse(content='OK', status=status.HTTP_200_OK)
                else:
                    logger.info(f"Something wrong!: {order_data}")
                    return JsonResponse({'message': 'The payment was made successfully, but the payment '
                                                    'status in the response is not successful! Impossible error.!'},
                                        status=status.HTTP_500_INTERNAL_SERVER_ERROR)
            else:
                return HttpResponse(content='OK', status=status.HTTP_200_OK)
        except ObjectDoesNotExist:
            logger.info("MISSING ORDER ERROR AGAIN!")
            return HttpResponse(content='OK', status=status.HTTP_200_OK)


class ChainsList(APIView):
    def get(self, request):
        if request.user.profile.subscription and request.user.profile.subscription.status():
            buy_on = (self.request.GET.get('buy_on', 'Купить на'), 'buy_on')

dev.p2ptradehelper/tradehelper/templates/tradehelper/app_header.html
{% load static %}
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
<link rel="stylesheet" type="text/css" href="{% static 'tradehelper/style1.1.css' %}">
<link rel="icon" type="image/x-icon" href="static/tradehelper/images/p2ptradehelper_logo.ico">
<meta charset="UTF-8">
<meta name="description" content="Инструмент для P2P арбитража - все возможные связки на биржах Binance, Huobi, Bybit, OKX, а также Bestchange">

dev.p2ptradehelper/tradehelper/templates/tradehelper/arbitration.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% include "tradehelper/app_header.html" %}
    <title>P2P Trade Helper | Ссылки на P2P связки для арбитража и торговли криптовалютами</title>
</head>
<body>
{% include "tradehelper/navbar.html" %}

<div style="display:flex; flex-direction: row; justify-content: left; align-items: center; margin-left: 100px;">
    <p style="color: #04DE34;"><i>Прибыльных связок: {{ all_chains }}</i></p>
</div>

<hr style="color: #D9D9D9; background-color: #EF6848; border: none; height: 1px; margin: 0;"/>

<form id="filter-form" method="get" action="{% url 'tradehelper:arbitration' %}">
    <div style="display:flex; flex-direction: row; justify-content: left; align-items: center; margin-left: 100px;" class="form-group">
        <label class="filter_label">
            <select id="buy_on" class="form-control" name="buy_on">
                <option value="Купить на" selected>Купить на</option>
                <option value="PochtaBank">PochtaBank</option>
                <option value="Yandex.Money">Yandex.Money</option>
                <option value="Raiffaizen">Raiffaizen</option>
                <option value="AlphaBank">AlphaBank</option>
                <option value="VTB">VTB</option>
                <option value="HomeCreditBank">HomeCreditBank</option>
                <option value="QiWi">QiWi</option>
                <option value="AkBarsBank">AkBarsBank</option>
                <option value="Rosbank">Rosbank</option>
                <option value="MTSBank">MTSBank</option>
                <option value="Tinkoff">Tinkoff</option>
                <option value="A-Bank">A-Bank</option>
                <option value="Gasprombank">Gasprombank</option>
                <option value="Sberbank">Sberbank</option>
            </select>
        </label>
        <label class="filter_label">
            <select id="sell_on" class="form-control" name="sell_on">
                <option value="Продать на" selected>Продать на</option>
                <option value="PochtaBank">PochtaBank</option>
                <option value="Yandex.Money">Yandex.Money</option>
                <option value="Raiffaizen">Raiffaizen</option>
                <option value="AlphaBank">AlphaBank</option>
                <option value="VTB">VTB</option>
                <option value="HomeCreditBank">HomeCreditBank</option>
                <option value="QiWi">QiWi</option>
                <option value="AkBarsBank">AkBarsBank</option>
                <option value="Rosbank">Rosbank</option>
                <option value="MTSBank">MTSBank</option>
                <option value="Tinkoff">Tinkoff</option>
                <option value="A-Bank">A-Bank</option>
                <option value="Gasprombank">Gasprombank</option>
                <option value="Sberbank">Sberbank</option>
            </select>
        </label>
        <label class="filter_label">
            <select id="coin" class="form-control" name="coin">
                <option value="Коин" selected>Коин</option>
                <option value="USDT">USDT</option>
                <option value="ETH">ETH</option>
                <option value="BTC">BTC</option>
                <option value="BUSD">BUSD</option>
                <option value="BNB">BNB</option>
            </select>
        </label>
        <label class="filter_label">
            <select id="buy_place" class="form-control" name="buy_place">
                <option value="Место покупки" selected>Место покупки</option>
                <option value="Binance">Binance</option>
                <option value="Huobi">Huobi</option>
                <option value="ByBit">ByBit</option>
                <option value="OKX">OKX</option>
                <option value="Bestchange">Bestchange</option>
            </select>
        </label>
        <label class="filter_label">
            <select id="sell_place" class="form-control" name="sell_place">
                <option value="Место продажи" selected>Место продажи</option>
                <option value="Binance">Binance</option>
                <option value="Huobi">Huobi</option>
                <option value="ByBit">ByBit</option>
                <option value="OKX">OKX</option>
                <option value="Bestchange">Bestchange</option>
            </select>
        </label>
        <label class="filter_label">
            <select id="buy_as" class="form-control" name="buy_as">
                <option value="Купить как" selected>Купить как</option>
                <option value="Тейкер">Тейкер</option>
                <option value="Мейкер">Мейкер</option>
            </select>
        </label>
        <label class="filter_label">
            <select id="sell_as" class="form-control" name="sell_as">
                <option value="Продать как" selected>Продать как</option>
                <option value="Тейкер">Тейкер</option>
                <option value="Мейкер">Мейкер</option>
            </select>
        </label>
        <input id="filter-button" type="submit" name="submit" value="Искать" class="btn shadow-none"/>
    </div>
</form>

<hr style="margin-left: 100px; margin-right: 100px; color: #EF6848; background-color: #EF6848; border: none; height: 1px"/>
<div class="column">
    {% for chain in chains %}
        <div style="display:flex; flex-direction: column; justify-content: center; align-items: flex-start;">
            <div class="row" style="display:flex; flex-direction: row; justify-content: space-between; align-items: center; margin-left: 100px; margin-right: 100px">
                <div style="display:flex; flex-direction: row; justify-content: center; align-items: center;">
                    <p style="margin: 5px 10px; color: #EF6848; font-size: 35px;"><b>{{ chain.buy_role }}</b></p>
                    <a target="_blank" rel="noopener noreferrer" href="{{ chain.buy_link }}" style="margin: 5px 10px; color: black;">{{ chain.buy_detail }}</a>
                    <p style="margin: 5px 10px; font-size: 40px; color: #EF6848;">➡</p>
                    <p style="margin: 5px 10px; color: #EF6848; font-size: 35px;"><b>{{ chain.sell_role }}</b></p>
                    <a target="_blank" rel="noopener noreferrer" href="{{ chain.sell_link }}" style="margin: 5px 10px; color: black;">{{ chain.sell_detail }}</a>
                </div>
                <p style="margin: 5px 10px; color: #04DE34;">{{ chain.profit_percent }} %</p>
            </div>
            <p style="margin-left: 165px; font-size: 15px; color: #777575;">Лимит покупки: {{ chain.buy_min_limit }} - {{ chain.buy_max_limit }}</p>
            <p style="margin-left: 165px; font-size: 15px; color: #777575;">Лимит продажи: {{ chain.sell_min_limit }} - {{ chain.sell_max_limit }}</p>
        </div>
        <hr style="margin-left: 100px; margin-right: 100px; color: #EF6848; background-color: #EF6848; border: none; height: 1px"/>
    {% endfor %}
</div>
</body>
</html>

dev.p2ptradehelper/tradehelper/templates/tradehelper/navbar.html
{% load static %}
<div id="main_navbar">
    <div id="navbar_list">
        <img id="app_icon" src="static/tradehelper/images/p2ptradehelper_logo.png" width="40px" height="40px" alt="Logo" style="margin-right: 20px;">
        <h1 id="header_text">P2P Trade Helper</h1>
    </div>
    <div id="navbar_list">
        <div class="topnav">
            <a href="{% url 'frontend:arbitration' %}">Арбитраж</a>
        </div>
        {% if user.profile.profile_photo %}
        <div class="circular">
            <a id="profile_link" href="{% url 'tradehelper:profile' %}"><img src='/{{ user.profile.profile_photo }}' alt="" /></a>
        </div>
        {% else %}
        <div class="circular">
            <a id="profile_link" href="{% url 'tradehelper:profile' %}"><img src='static/tradehelper/images/account_circle_white_48dp.svg' alt="" /></a>
        </div>
        {% endif %}
    </div>
</div>
<div id="navbar_bottom_strip">
</div>

dev.p2ptradehelper/tradehelper/templates/tradehelper/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% include "tradehelper/app_header.html" %}
    <title>P2P Trade Helper | Ссылки на P2P связки для арбитража и торговли криптовалютами</title>
</head>
<body onload="
    const inputs = document.getElementsByTagName('input');
    for (let i=0; i<inputs.length; i++)  {
        if (inputs[i].type === 'checkbox')   {
            inputs[i].checked = false;
        }
    }">
{% include "tradehelper/navbar.html" %}
<div id="profile_flex">
    <div id="profile_photo_box">
        {% if user.profile.profile_photo %}
            <img class="profile_photo" src='{{ user.profile.profile_photo }}' alt="">
        {% else %}
            <img class="profile_photo" src='static/tradehelper/images/account_circle_white_48dp.svg' alt="">
        {% endif %}
    </div>
    <div id="user_data">
        <div id="profile_edit_box">
            <h1 id="user_nickname">{{ user.get_username }}</h1>
            <a id="edit_button" href="{% url 'tradehelper:edit_profile' %}"><img class="image_icon" src="{% static 'tradehelper/images/edit_white_48dp.svg' %}" alt=""></a>
        </div>
        <p id="user_full_name">{{ user.get_full_name }}</p>
        <p id="user_email">{{ user.email }}</p>
        {% if user.profile.subscription.status %}
            <p id="user_subscription">Подписка: {{ user.profile.subscription }}</p>
        {% else %}
            <p id="user_subscription">Подписка: не подключена</p>
        {% endif %}
    </div>
</div>
{% if not user.profile.subscription %}
    <div class="accordion" id="accordionExample" style="margin: 1rem;">
        <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button shadow-none" type="button" style="color: #FF9C51; background: white; font-size: 20px" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    Базовая подписка
                </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                <ul>
                    <li><p style="color: #181818; font-size: 15px;">Доступ к списку всех связок на странице арбитража</p></li>
                    <li><p style="color: #181818; font-size: 15px;">Возможность фильтрации связок по нужным параметрам</p></li>
                    <li><p style="color: #181818; font-size: 15px;">Переход по ссылке прямо к продаже или покупке</p></li>
                    <li><p style="color: #181818; font-size: 15px;">Обновление всех связок раз в минуту и быстрее</p></li>
                    <p style="color: #FF9C51; font-size: 20px; margin-top:1rem;"><b>990₽</b></p>
                </ul>
                <div id="subscr_container" style="display: flex; margin-top: 1rem; margin-bottom: 1rem;">
                    <button id="button_subscr" style="height: fit-content; color: white; background: #181818;" onclick="location.href='{% url 'tradehelper:buy_subscription'%}'" type="button" class="btn shadow-none" disabled="disabled">Купить подписку</button>
                    <label class="form-check-label" for="flexCheckDefault" style="margin-left: 20px;">
                        <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault" onchange="document.getElementById('button_subscr').disabled = !this.checked;">
                        <a id="rules_link" href="{% url 'tradehelper:autopay_rules'%}" style="color: #FF9C51;">Согласен с условиями оферты рекуррентных платежей</a>
                        <p id="next_payment" style="color: #FF9C51">Дата следующего списания: {{ next_payment_date }}</p>
                    </label>
                </div>
            </div>
        </div>
    </div>
{% endif %}
{% if user.is_authenticated %}
    <a id="button_logout" href="{% url 'tradehelper:logout'%}?next={{request.path}}" type="button" class="btn shadow-none" style="color: white; background: #181818">Выйти</a>
{% endif %}
{% if user.profile.subscription and not user.profile.subscription.canceled %}
    <button id="button_subscr" style="height: fit-content; color: white; background: #181818;" onclick="location.href='{% url 'tradehelper:unsubscribe'%}'" type="button" class="btn shadow-none">Отписаться</button>
{% endif %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

</body>
</html>

dev.p2ptradehelper/tradehelper/templates/tradehelper/success_payment.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% include "tradehelper/app_header.html" %}
    <title>P2P Trade Helper | Ссылки на P2P связки для арбитража и торговли криптовалютами</title>
</head>
<body>
{% include "tradehelper/navbar.html" %}
<div id="login_container">
    <div id="success_form">
        <div id="login_form_header">
            <div style="display: flex; justify-content: center;">
                <h1 id="header_text">P2P Trade Helper</h1>
            </div>
            <h5 style="color:white;">Платёж выполнен!</h5>
        </div>
        <div style="display: flex; justify-content: center;">
            <a href="{% url 'frontend:arbitration'%}" style="margin: 1rem; color: white;">Перейти на страницу арбитража</a>
        </div>
    </div>
</div>
</body>
</html>